### Get all blog posts
GET http://localhost:3001/api/blogs

### Create a new blog post
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "My new blog post",
  "author": "John Dohn",
  "url": "http://example.com/my-new-blog-post"
}

### DELETE a blog (change id as needed)
DELETE http://localhost:3001/api/blogs/7

### Update a blog (change id as needed)
PUT http://localhost:3001/api/blogs/8
Content-Type: application/json

{
  "likes": 5
}

### Create a new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "sona",
  "username": "hello"
}